export enum IdentityDocumentType {
  REGISTRO_CIVIL = 1,
  TARJETA_IDENTIDAD = 2,
  CEDULA_CIUDADANIA = 3,
  TARJETA_EXTRANJERIA = 4,
  CEDULA_EXTRANJERIA = 5,
  NIT = 6,
  PASAPORTE = 7,
  DOCUMENTO_EXTRANJERO = 8,
  PEP = 9,
  NIT_OTRO_PAIS = 10,
  NUIP = 11,
}