export enum Tribute {
  IVA = 1,
  IC = 2,
  ICA = 3,
  INC = 4,
  ReteIVA = 5,
  ReteRenta = 6,
  ReteICA = 7,
  IC_PORCENTUAL = 8,
  FTOHORTICULTURA = 9,
  TIMBRE = 10,
  INC_BOLSAS = 11,
  INCARBONO = 12,
  INCARBONO2 = 13,
  INCOMBUSTIBLES = 14,
  SOBRETASA_COMBUSTIBLES = 15,
  SORDICOM = 16,
  IC_DATOS = 17,
} 